import Image from "next/image";
import Link from "next/link";
import { ArrowLeft, ArrowRight, BookOpen, Boxes, FlaskConical, Lightbulb, Network, Rocket, Search } from "lucide-react";
import type { Project } from "@/lib/projects";
import { Header } from "./header";

const researchLens = (project: Project) => project.category.includes("CUDA") || project.category.includes("GPU")
  ? "memory traffic, kernel fusion, occupancy, numerical stability, and hardware-aware scheduling"
  : project.category.includes("Reinforcement")
    ? "sample efficiency, exploration, off-policy correction, model-based planning, and robust evaluation"
    : project.category.includes("LLM") || project.category.includes("Generative") || project.category.includes("Alignment")
      ? "scaling behavior, data quality, controllability, evaluation, inference efficiency, and safety"
      : project.category.includes("Distributed") || project.category.includes("Federated") || project.category.includes("Systems")
        ? "communication cost, memory pressure, fault tolerance, scheduling, privacy, and reproducibility"
        : "statistical assumptions, optimization, generalization, uncertainty, data quality, and interpretability";

export function ProjectArticle({ project }: { project: Project }) {
  return <main className="app-shell reading-shell"><Header active="projects"/><article className="research-article">
    <Link className="back" href={`/projects/${project.slug}`}><ArrowLeft/> Project overview</Link>
    <header className="article-hero"><div><span className="kicker">FIRST-PRINCIPLES FIELD GUIDE</span><h1>{project.title}</h1><p>{project.description}</p><div className="article-meta"><span>{project.category}</span><span>{project.framework}</span><span>{project.steps} implementation lessons</span></div></div><div className="article-cover"><Image src={`/project-art/${project.slug}.svg`} alt="" fill priority/></div></header>
    <nav className="article-toc"><strong>In this guide</strong><a href="#why">Why it exists</a><a href="#principles">First principles</a><a href="#concepts">Concepts</a><a href="#use-cases">Use cases</a><a href="#research">Research evolution</a><a href="#roadmap">Study roadmap</a></nav>
    <section id="why"><span className="reading-icon"><Lightbulb/></span><small>01 · MOTIVATION</small><h2>Begin with the problem, not the library</h2><p>Before {project.title} is a collection of classes and functions, it is an answer to a constraint. {project.description} The useful question is not “which API should I call?” but “what information is available, what decision must be made, and what evidence proves the decision is good?”</p><p>A first-principles implementation makes hidden assumptions visible. It forces us to specify the input, the transformation, the objective, and the failure conditions. That discipline is valuable even when a production system later uses a mature library.</p><aside><strong>Core contract</strong><p>Transform well-defined inputs into measurable outputs while preserving the invariants required by the next stage.</p></aside></section>
    <section id="principles"><span className="reading-icon"><Boxes/></span><small>02 · FIRST PRINCIPLES</small><h2>Reduce the system to four questions</h2><div className="principle-grid">{[["Representation","How is the raw problem expressed as numbers, states, tokens, tensors, or events?"],["Objective","What quantity tells the system that one answer is better than another?"],["Update","How does evidence change parameters, state, policy, or decisions?"],["Evaluation","Which controlled test separates real improvement from noise or leakage?"]].map(([title,copy],i)=><article key={title}><b>0{i+1}</b><h3>{title}</h3><p>{copy}</p></article>)}</div><p>{project.title} becomes understandable when each implementation step answers exactly one of these questions. The walkthrough keeps those boundaries explicit so a bug can be localized instead of disappearing inside an end-to-end pipeline.</p></section>
    <section id="concepts"><span className="reading-icon"><BookOpen/></span><small>03 · CONCEPT ATLAS</small><h2>The ideas you must genuinely understand</h2>{project.concepts.map((concept,index)=><div className="concept-essay" key={concept}><b>{String(index+1).padStart(2,"0")}</b><div><h3>{concept}</h3><p>{concept} is not an isolated trick. It controls how information moves through {project.title}, what the system can represent, and where errors appear. Start with a tiny hand-computable example; write down shapes and legal ranges; then compare the implementation with that reference before scaling.</p><p className="muted">Verification rule: test the normal case, a boundary case, an invalid case, and an invariant that must remain true after the operation.</p></div></div>)}</section>
    <section id="use-cases"><span className="reading-icon"><Rocket/></span><small>04 · REAL-WORLD USE</small><h2>Where this pattern becomes useful</h2><div className="use-case-grid">{project.skills.map((skill,i)=><article key={skill}><FlaskConical/><h3>{skill}</h3><p>Use this capability when the product must make repeatable decisions under the same structural constraints studied in the project. Begin with an offline baseline, define a business-facing metric, and add monitoring before automation.</p><span>Use case {i+1}</span></article>)}</div><aside><strong>Production warning</strong><p>A benchmark result is not deployment readiness. Check data drift, latency, cost, observability, privacy, abuse cases, rollback behavior, and human escalation paths.</p></aside></section>
    <section id="research"><span className="reading-icon"><Search/></span><small>05 · RESEARCH EVOLUTION</small><h2>How the field keeps improving</h2><p>The modern research frontier around {project.title} concentrates on {researchLens(project)}. Improvements usually come from changing one of four levers: a better representation, a better learning signal, a more efficient computation path, or a more honest evaluation protocol.</p><div className="timeline"><article><b>Foundation</b><p>Formalize the task, objective, and simplest correct baseline.</p></article><article><b>Scale</b><p>Improve data, optimization, hardware use, and numerical reliability.</p></article><article><b>Modern frontier</b><p>Combine efficiency with robustness, controllability, and stronger evaluation.</p></article><article><b>Open questions</b><p>Identify cases where current assumptions fail, costs explode, or metrics reward the wrong behavior.</p></article></div><p className="muted">Research changes quickly. Treat paper claims as hypotheses: reproduce the baseline, inspect ablations, compare compute budgets, and verify whether the evaluation matches your intended use.</p></section>
    <section id="roadmap"><span className="reading-icon"><Network/></span><small>06 · AFTER THE BUILD</small><h2>Your next-study roadmap</h2><ol className="study-roadmap"><li><b>Re-derive</b><p>Explain each core equation without looking at the code.</p></li><li><b>Rebuild</b><p>Implement the smallest version again from an empty file.</p></li><li><b>Stress test</b><p>Create adversarial, boundary, numerical, and distribution-shift tests.</p></li><li><b>Read critically</b><p>Choose one foundational paper and two recent follow-ups; reproduce one reported comparison.</p></li><li><b>Extend</b><p>Change one assumption, record the hypothesis, and run a controlled experiment.</p></li><li><b>Publish</b><p>Document architecture, tradeoffs, failures, metrics, cost, and reproducible commands.</p></li></ol><div className="reading-actions"><Link href={`/projects/${project.slug}/architecture`}>Explore the architecture <ArrowRight/></Link><Link href={`/walkthrough/${project.slug}`}>Start the implementation <ArrowRight/></Link></div></section>
  </article></main>;
}

export function ProjectArchitecture({ project }: { project: Project }) {
  const alpha = project.slug === "alphazero-on-connect-4-from-scratch";
  return <main className="app-shell reading-shell"><Header active="projects"/><article className="architecture-page">
    <Link className="back" href={`/projects/${project.slug}`}><ArrowLeft/> Project overview</Link>
    <header><span className="kicker">SYSTEM ARCHITECTURE</span><h1>{project.title}</h1><p>Follow the data, decisions, feedback, and validation boundaries before writing the full system.</p></header>
    <section className="architecture-visual">{alpha?<Image src="/generated/alphazero-connect4-architecture.png" alt="AlphaZero Connect-4 architecture showing board encoding, policy-value network, PUCT search, self-play data, and training feedback loop" width={1792} height={1024} priority/>:<><div className="arch-flow">{project.concepts.map((concept,i)=><div key={concept}><span>{String(i+1).padStart(2,"0")}</span><strong>{concept}</strong><small>{i===0?"Represent and validate inputs":i===project.concepts.length-1?"Measure output and feed learning back":"Transform state with a testable contract"}</small>{i<project.concepts.length-1&&<i>→</i>}</div>)}</div><div className="arch-feedback">evaluation feedback ↺</div></>}</section>
    <section className="arch-explanation"><h2>How to read this diagram</h2><p>Read left to right for the forward path: raw information becomes a representation, passes through the project’s main computational ideas, and produces an output that can be measured. Then follow the feedback path back toward the trainable or decision-making components.</p><div>{project.concepts.map((concept,i)=><article key={concept}><b>{String(i+1).padStart(2,"0")}</b><h3>{concept}</h3><p>This boundary owns one transformation. Record accepted inputs, output shape, mutable state, failure modes, and the metric that confirms correctness. Keep it independently testable before connecting it to the next component.</p></article>)}</div></section>
    <section className="arch-checklist"><h2>Architecture review checklist</h2><ul><li>Every arrow has a documented shape, dtype, unit, or schema.</li><li>Training and evaluation paths cannot leak information into each other.</li><li>Randomness is seeded and captured in experiment metadata.</li><li>Expensive stages expose timing, memory, throughput, and error metrics.</li><li>Each feedback loop has a stop condition and a rollback strategy.</li><li>Small reference implementations exist for numerical comparisons.</li></ul></section>
    <div className="reading-actions"><Link href={`/projects/${project.slug}/article`}>Read the first-principles guide <ArrowRight/></Link><Link href={`/walkthrough/${project.slug}`}>Build it step by step <ArrowRight/></Link></div>
  </article></main>;
}
