import Image from "next/image";
import Link from "next/link";
import { ArrowLeft, ArrowRight, BookOpen, Boxes, FlaskConical, Lightbulb, Network, Rocket, Search } from "lucide-react";
import type { Project } from "@/lib/projects";
import researchJson from "@/lib/research.generated.json";
import { Header } from "./header";

const researchLens = (project: Project) => project.category.includes("CUDA") || project.category.includes("GPU")
  ? "memory traffic, kernel fusion, occupancy, numerical stability, and hardware-aware scheduling"
  : project.category.includes("Reinforcement")
    ? "sample efficiency, exploration, off-policy correction, model-based planning, and robust evaluation"
    : project.category.includes("LLM") || project.category.includes("Generative") || project.category.includes("Alignment")
      ? "scaling behavior, data quality, controllability, evaluation, inference efficiency, and safety"
      : project.category.includes("Distributed") || project.category.includes("Federated") || project.category.includes("Systems")
        ? "communication cost, memory pressure, fault tolerance, scheduling, privacy, and reproducibility"
        : "statistical assumptions, optimization, generalization, uncertainty, data quality, and interpretability";

type ResearchEntry = {slug:string;research_evolution:string;sources:Array<{title:string;url:string;year:number|string;contribution:string;limitations_current_improvement_angle:string}>};
const researchBySlug = new Map((researchJson as ResearchEntry[]).map((entry)=>[entry.slug,entry]));

function conceptPrimer(concept: string) {
  const c = concept.toLowerCase();
  if (c.includes("gini")) return "Gini impurity is the probability of misclassifying a label drawn from a node when the label is sampled from that node’s class distribution. A pure node has impurity zero. A split is useful only when the sample-weighted impurity of its children is lower than the parent’s impurity.";
  if (c.includes("bagging") || c.includes("bootstrap")) return "Bagging trains estimators on bootstrap samples drawn with replacement. Each learner sees a slightly different empirical distribution. Averaging their predictions keeps shared signal while cancelling part of their uncorrelated variance.";
  if (c.includes("attention")) return "Attention builds a content-dependent weighted average. Queries describe what each position needs, keys describe what each position offers, and values carry the information. Scaling by the square root of key dimension prevents dot products from pushing softmax into saturation.";
  if (c.includes("positional")) return "Attention alone is permutation-equivariant, so it cannot know token order. Positional features inject location into the representation, either as fixed sinusoids, learned vectors, rotations such as RoPE, or relative biases.";
  if (c.includes("bellman") || c.includes("q-table") || c.includes("bootstrapping")) return "The Bellman relationship decomposes long-term value into immediate reward plus discounted value of what follows. Bootstrapping replaces the unknown future return with the learner’s current estimate, which improves data efficiency but can amplify estimation error.";
  if (c.includes("puct") || c.includes("mcts")) return "PUCT balances exploitation of actions with high mean value and exploration of actions favored by the policy prior but visited less often. Repeated selection, expansion, evaluation, and backup turns neural estimates into a stronger search policy.";
  if (c.includes("value network")) return "A value network compresses the expected outcome of a state into one scalar from the current player’s perspective. Perspective must flip during tree backup; otherwise an action good for the opponent is accidentally reinforced.";
  if (c.includes("replay")) return "A replay store breaks temporal correlation and lets expensive experience support multiple gradient updates. Its schema, sampling policy, age distribution, and target semantics are part of the algorithm—not mere storage details.";
  if (c.includes("vector search") || c.includes("embedding")) return "Embeddings map items into a geometry where distance approximates semantic relatedness. Retrieval compares a query vector with document vectors, but useful systems also handle lexical matches, metadata filters, reranking, and evidence attribution.";
  if (c.includes("rerank")) return "A reranker spends more computation on a small candidate set. Unlike a dual encoder that scores items independently, a cross-encoder can inspect query and document jointly and model fine-grained relevance.";
  if (c.includes("grounded")) return "Grounded generation conditions an answer on retrieved evidence and requires claims to remain supported by that evidence. Retrieval quality, context packing, citation alignment, abstention, and faithfulness must be evaluated separately.";
  if (c.includes("lora")) return "LoRA freezes a base weight matrix and learns a low-rank update BA. The rank limits trainable capacity and memory cost; placement, scaling, initialization, and target modules determine whether the adapter can express the required behavior.";
  if (c.includes("quant")) return "Quantization represents values with fewer bits using a scale and zero point or symmetric range. It reduces memory traffic and storage, but outliers, accumulation precision, calibration, and dequantization overhead control real quality and speed.";
  if (c.includes("dpo") || c.includes("preference")) return "Preference optimization learns from chosen and rejected responses. DPO converts a Bradley–Terry preference model into a stable classification-style objective relative to a frozen reference policy, avoiding an explicit reward-model-plus-RL loop.";
  if (c.includes("convolution") || c.includes("im2col")) return "A convolution shares a local kernel across spatial positions. im2col unfolds receptive fields into matrix columns so the forward pass becomes GEMM; the backward pass must scatter overlapping column gradients back to the image.";
  if (c.includes("pool")) return "Pooling summarizes a local neighborhood to reduce spatial resolution. Max pooling routes gradient only to the recorded argmax, making index caching and tie behavior important for a correct backward pass.";
  if (c.includes("adam")) return "Adam tracks exponential moving averages of gradients and squared gradients, applies bias correction early in training, and scales each parameter update by its estimated second moment. Epsilon placement and weight-decay semantics matter.";
  if (c.includes("kv cache")) return "Autoregressive decoding reuses keys and values from previous tokens. A KV cache changes attention from repeatedly recomputing history to appending one position, trading memory capacity and movement for lower token latency.";
  if (c.includes("paged")) return "Paged allocation stores sequence cache blocks non-contiguously and maps logical token positions to physical pages. This reduces fragmentation and enables sharing, but adds metadata, lookup, eviction, and scheduling complexity.";
  if (c.includes("continuous batch")) return "Continuous batching admits and retires sequences at iteration boundaries instead of waiting for a fixed batch to finish. Throughput improves, while fairness, memory admission, cancellation, and tail latency become scheduling problems.";
  if (c.includes("tiling") || c.includes("memory hierarchy")) return "Tiling moves a reusable working set from slow global memory into shared memory and registers. Correct tile boundaries come first; performance then depends on coalescing, bank conflicts, occupancy, synchronization, and arithmetic intensity.";
  if (c.includes("online softmax")) return "Online softmax maintains a running row maximum and rescaled exponential sum. When a new tile has a larger maximum, earlier partial sums are corrected, allowing exact stable softmax without storing the complete score matrix.";
  if (c.includes("fedavg")) return "FedAvg lets clients perform local SGD and combines their parameters with weights proportional to client sample counts. Local work saves communication, but heterogeneous client data causes update drift and changes the optimization problem.";
  if (c.includes("non-iid")) return "Non-IID data means clients or shards follow different distributions. It tests whether aggregation remains stable when local gradients disagree and whether reported global accuracy hides poor subgroup behavior.";
  if (c.includes("checkpoint")) return "Activation checkpointing discards selected forward intermediates and recomputes them during backward. It trades extra arithmetic for lower peak memory and requires deterministic replay of any stochastic operation inside a checkpointed region.";
  if (c.includes("mixed precision")) return "Mixed precision stores or computes many tensors in lower precision while preserving sensitive reductions and master weights at higher precision. Loss scaling protects small gradients from underflow; overflow detection decides whether an update is safe.";
  if (c.includes("zero")) return "ZeRO removes replicated training state by partitioning optimizer tensors, gradients, and eventually parameters across workers. Each stage saves more memory while introducing communication and lifetime-management constraints.";
  if (c.includes("autograd") || c.includes("reverse")) return "Reverse-mode automatic differentiation records primitive operations and local derivative rules, then traverses the graph backward while accumulating gradients from every downstream path. Broadcasting must be reversed by summing expanded axes.";
  if (c.includes("lazy")) return "Lazy execution records operations before materializing results. This enables fusion and scheduling, but requires explicit realization boundaries, shape inference, cache invalidation, and a clear policy for side effects.";
  if (c.includes("vq-vae") || c.includes("discrete token")) return "A VQ-VAE maps continuous encoder outputs to the nearest learned codebook vectors. The discrete indices become image tokens; commitment and codebook updates prevent the encoder or dictionary from drifting apart.";
  if (c.includes("classifier-free")) return "Classifier-free guidance trains conditional and unconditional predictions in one model. Sampling extrapolates away from the unconditional prediction, increasing prompt alignment while too much guidance reduces diversity and can distort samples.";
  if (c.includes("causal") || c.includes("sampling")) return "Autoregressive modeling factorizes a sequence into next-token conditional probabilities. A causal mask blocks future information; temperature, top-k, and nucleus sampling reshape the distribution at inference without retraining.";
  if (c.includes("minimax")) return "Minimax assumes optimal adversarial play: maximize value on your turn and minimize it on the opponent’s turn. Terminal scoring, player perspective, transposition caching, and alpha–beta bounds determine correctness and efficiency.";
  if (c.includes("dqn")) return "DQN approximates action values with a neural network, trains from replay, and uses a slower target network to reduce moving-target instability. Legal-action masking, exploration, and overestimation bias are central details.";
  if (c.includes("power") || c.includes("did") || c.includes("synthetic control")) return "Causal estimation separates treatment effect from ordinary variation by stating an identification assumption. Power, parallel trends, interference, pre-treatment fit, and multiple testing must be checked before interpreting a p-value or effect estimate.";
  return `${concept} defines one of the project’s main information transformations. Understand its input representation, objective, numerical invariants, computational cost, and failure modes before relying on a library implementation.`;
}

export function ProjectArticle({ project }: { project: Project }) {
  const research = researchBySlug.get(project.slug);
  return <main className="app-shell reading-shell"><Header active="projects"/><article className="research-article">
    <Link className="back" href={`/projects/${project.slug}`}><ArrowLeft/> Project overview</Link>
    <header className="article-hero"><div><span className="kicker">FIRST-PRINCIPLES FIELD GUIDE</span><h1>{project.title}</h1><p>{project.description}</p><div className="article-meta"><span>{project.category}</span><span>{project.framework}</span><span>{project.steps} implementation lessons</span></div></div><div className="article-cover"><Image src={`/project-art/${project.slug}.svg`} alt="" fill priority/></div></header>
    <nav className="article-toc"><strong>In this guide</strong><a href="#why">Why it exists</a><a href="#principles">First principles</a><a href="#concepts">Concepts</a><a href="#use-cases">Use cases</a><a href="#research">Research evolution</a><a href="#roadmap">Study roadmap</a></nav>
    <section id="why"><span className="reading-icon"><Lightbulb/></span><small>01 · MOTIVATION</small><h2>Begin with the problem, not the library</h2><p>Before {project.title} is a collection of classes and functions, it is an answer to a constraint. {project.description} The useful question is not “which API should I call?” but “what information is available, what decision must be made, and what evidence proves the decision is good?”</p><p>A first-principles implementation makes hidden assumptions visible. It forces us to specify the input, the transformation, the objective, and the failure conditions. That discipline is valuable even when a production system later uses a mature library.</p><aside><strong>Core contract</strong><p>Transform well-defined inputs into measurable outputs while preserving the invariants required by the next stage.</p></aside></section>
    <section id="principles"><span className="reading-icon"><Boxes/></span><small>02 · FIRST PRINCIPLES</small><h2>Reduce the system to four questions</h2><div className="principle-grid">{[["Representation","How is the raw problem expressed as numbers, states, tokens, tensors, or events?"],["Objective","What quantity tells the system that one answer is better than another?"],["Update","How does evidence change parameters, state, policy, or decisions?"],["Evaluation","Which controlled test separates real improvement from noise or leakage?"]].map(([title,copy],i)=><article key={title}><b>0{i+1}</b><h3>{title}</h3><p>{copy}</p></article>)}</div><p>{project.title} becomes understandable when each implementation step answers exactly one of these questions. The walkthrough keeps those boundaries explicit so a bug can be localized instead of disappearing inside an end-to-end pipeline.</p></section>
    <section id="concepts"><span className="reading-icon"><BookOpen/></span><small>03 · CONCEPT ATLAS</small><h2>The ideas you must genuinely understand</h2>{project.concepts.map((concept,index)=><div className="concept-essay" key={concept}><b>{String(index+1).padStart(2,"0")}</b><div><h3>{concept}</h3><p>{conceptPrimer(concept)}</p><p>In {project.title}, implement this idea first on a tiny hand-computable example. Write down every shape, legal range, and invariant; compare the code with the manual result; then profile and scale only after the reference agrees.</p><p className="muted">Verification rule: test the normal case, a boundary case, an invalid case, and an invariant that must remain true after the operation.</p></div></div>)}</section>
    <section id="use-cases"><span className="reading-icon"><Rocket/></span><small>04 · REAL-WORLD USE</small><h2>Where this pattern becomes useful</h2><div className="use-case-grid">{project.skills.map((skill,i)=><article key={skill}><FlaskConical/><h3>{skill}</h3><p>Use this capability when the product must make repeatable decisions under the same structural constraints studied in the project. Begin with an offline baseline, define a business-facing metric, and add monitoring before automation.</p><span>Use case {i+1}</span></article>)}</div><aside><strong>Production warning</strong><p>A benchmark result is not deployment readiness. Check data drift, latency, cost, observability, privacy, abuse cases, rollback behavior, and human escalation paths.</p></aside></section>
    <section id="research"><span className="reading-icon"><Search/></span><small>05 · RESEARCH EVOLUTION</small><h2>How the field keeps improving</h2><p>{research?.research_evolution ?? `The modern research frontier around ${project.title} concentrates on ${researchLens(project)}.`}</p><p>Improvements usually change one of four levers: representation, learning signal, computation path, or evaluation protocol. Read each source with its assumptions and comparison budget in view.</p><div className="research-sources">{research?.sources.map((source)=><a key={source.url} href={source.url} target="_blank" rel="noreferrer"><header><b>{source.year}</b><span>Primary source ↗</span></header><h3>{source.title}</h3><p>{source.contribution}</p><aside><strong>Limitation and current direction</strong><p>{source.limitations_current_improvement_angle}</p></aside></a>)}</div><p className="muted">Treat paper claims as hypotheses: reproduce the baseline, inspect ablations, normalize compute budgets, and verify whether the evaluation matches your intended use.</p></section>
    <section id="roadmap"><span className="reading-icon"><Network/></span><small>06 · AFTER THE BUILD</small><h2>Your next-study roadmap</h2><ol className="study-roadmap"><li><b>Re-derive</b><p>Explain each core equation without looking at the code.</p></li><li><b>Rebuild</b><p>Implement the smallest version again from an empty file.</p></li><li><b>Stress test</b><p>Create adversarial, boundary, numerical, and distribution-shift tests.</p></li><li><b>Read critically</b><p>Choose one foundational paper and two recent follow-ups; reproduce one reported comparison.</p></li><li><b>Extend</b><p>Change one assumption, record the hypothesis, and run a controlled experiment.</p></li><li><b>Publish</b><p>Document architecture, tradeoffs, failures, metrics, cost, and reproducible commands.</p></li></ol><div className="reading-actions"><Link href={`/projects/${project.slug}/architecture`}>Explore the architecture <ArrowRight/></Link><Link href={`/walkthrough/${project.slug}`}>Step-by-step walkthrough <ArrowRight/></Link><a href={`https://github.com/shivam2003-dev/ml-learning-journey/blob/main/implementations/${project.slug}/tutorial.ipynb`} target="_blank" rel="noreferrer">Run the complete notebook <ArrowRight/></a><a href={`https://github.com/shivam2003-dev/ml-learning-journey/tree/main/implementations/${project.slug}`} target="_blank" rel="noreferrer">Production pipeline <ArrowRight/></a></div></section>
  </article></main>;
}

export function ProjectArchitecture({ project }: { project: Project }) {
  const generatedVisuals: Record<string, string> = {
    "alphazero-on-connect-4-from-scratch": "/generated/alphazero-connect4-architecture.png",
    "random-forest-from-scratch": "/generated/random-forest-architecture.png",
    "support-vector-machine-from-scratch": "/generated/svm-architecture.png",
    "build-a-trainable-cnn-from-scratch-in-numpy": "/generated/cnn-numpy-architecture.png",
    "attention-is-all-you-need-build-the-transformer-from-scratch": "/generated/transformer-architecture.png",
    "tiny-gpt-from-scratch": "/generated/tiny-gpt-architecture.png",
    "q-learning-on-frozenlake-from-scratch": "/generated/q-learning-frozenlake-architecture.png",
    "build-a-retrieval-augmented-generation-pipeline-from-scratch": "/generated/rag-architecture.png",
    "direct-preference-optimization-dpo-from-scratch": "/generated/dpo-architecture.png",
    "rlhf-from-scratch-on-distilgpt2": "/generated/rlhf-architecture.png",
    "vision-language-model-from-scratch-in-pytorch": "/generated/vlm-architecture.png",
    "flash-attention-in-cuda-from-scratch": "/generated/flash-attention-architecture.png",
    "fused-llm-inference-kernels-in-cuda": "/generated/fused-llm-kernels-architecture.png",
    "build-a-mini-llm-inference-server": "/generated/mini-llm-server-architecture.png",
    "verillm-publicly-verifiable-decentralized-llm-inference-from-scr": "/generated/verillm-architecture.png",
    "build-an-mlp-in-jax-from-scratch": "/generated/jax-mlp-architecture.png",
    "build-your-own-teenygrad-a-tiny-tensor-autograd-engine": "/generated/teenygrad-architecture.png",
    "federated-averaging-fedavg-from-scratch-in-pytorch": "/generated/fedavg-architecture.png",
    "diloco-distributed-low-communication-training-of-language-models": "/generated/diloco-architecture.png",
    "mini-distributed-training-and-memory-constrained-trainer-from-sc": "/generated/memory-trainer-architecture.png",
    "trainable-mixture-of-experts-in-cuda": "/generated/moe-cuda-architecture.png",
    "multimodal-autoregressive-image-generator-from-scratch-in-jax": "/generated/multimodal-image-generator-architecture.png",
    "lora-fine-tune-a-tiny-chat-model-with-unsloth": "/generated/lora-unsloth-architecture.png",
    "a-b-testing-causal-inference-toolkit": "/generated/causal-inference-architecture.png",
    "market-making-betting-game-simulator": "/generated/market-making-architecture.png",
    "reinforcement-learning-for-tic-tac-toe-from-minimax-to-dqn": "/generated/tictactoe-dqn-architecture.png",
  };
  const generatedVisual = generatedVisuals[project.slug];
  return <main className="app-shell reading-shell"><Header active="projects"/><article className="architecture-page">
    <Link className="back" href={`/projects/${project.slug}`}><ArrowLeft/> Project overview</Link>
    <header><span className="kicker">SYSTEM ARCHITECTURE</span><h1>{project.title}</h1><p>Follow the data, decisions, feedback, and validation boundaries before writing the full system.</p></header>
    <section className="architecture-visual">{generatedVisual?<Image src={generatedVisual} alt={`${project.title} first-principles architecture infographic`} width={1792} height={1024} priority/>:<><div className="arch-flow">{project.concepts.map((concept,i)=><div key={concept}><span>{String(i+1).padStart(2,"0")}</span><strong>{concept}</strong><small>{i===0?"Represent and validate inputs":i===project.concepts.length-1?"Measure output and feed learning back":"Transform state with a testable contract"}</small>{i<project.concepts.length-1&&<i>→</i>}</div>)}</div><div className="arch-feedback">evaluation feedback ↺</div></>}</section>
    <section className="arch-explanation"><h2>How to read this diagram</h2><p>Read left to right for the forward path: raw information becomes a representation, passes through the project’s main computational ideas, and produces an output that can be measured. Then follow the feedback path back toward the trainable or decision-making components.</p><div>{project.concepts.map((concept,i)=><article key={concept}><b>{String(i+1).padStart(2,"0")}</b><h3>{concept}</h3><p>{conceptPrimer(concept)}</p><p className="muted">Boundary check: document its accepted input, output shape, mutable state, failure modes, and the metric that proves this stage is correct before connecting it downstream.</p></article>)}</div></section>
    <section className="arch-checklist"><h2>Architecture review checklist</h2><ul><li>Every arrow has a documented shape, dtype, unit, or schema.</li><li>Training and evaluation paths cannot leak information into each other.</li><li>Randomness is seeded and captured in experiment metadata.</li><li>Expensive stages expose timing, memory, throughput, and error metrics.</li><li>Each feedback loop has a stop condition and a rollback strategy.</li><li>Small reference implementations exist for numerical comparisons.</li></ul></section>
    <div className="reading-actions"><Link href={`/projects/${project.slug}/article`}>Read the first-principles guide <ArrowRight/></Link><Link href={`/walkthrough/${project.slug}`}>Build it step by step <ArrowRight/></Link></div>
  </article></main>;
}
