import type { Project } from "./projects";

export type MathTopic = {
  title: string;
  intuition: string;
  equation: string;
  symbols: Array<[string, string]>;
  derivation: string[];
  workedExample: string;
  codeBridge: string[];
  stability: string;
};

function topicFor(concept: string): Omit<MathTopic, "title"> {
  const c = concept.toLowerCase();
  if (c.includes("gini")) return { intuition:"Impurity measures how mixed the labels inside a node are. Squared class probabilities reward concentration: one class with probability one produces zero impurity.", equation:String.raw`G(S)=1-\sum_{k=1}^{K}p_k^2,\qquad \Delta G=G(S)-\frac{n_L}{n}G(S_L)-\frac{n_R}{n}G(S_R)`, symbols:[["S","samples reaching the node"],["p_k","fraction belonging to class k"],["S_L,S_R","left and right child samples"],["n_L,n_R","child sample counts"]], derivation:["Convert class counts into probabilities.","Square and sum those probabilities.","Subtract the concentration from one.","Compute child impurities with the same rule.","Weight children by sample count and subtract from the parent."], workedExample:"For labels [A,A,A,B], p(A)=3/4 and p(B)=1/4, so G=1-(9/16+1/16)=6/16=0.375. A perfect split creates pure children and therefore gains 0.375 impurity units.", codeBridge:["Use bincount to obtain class counts.","Divide by the number of labels in the node.","Return zero for an empty or pure node according to the caller contract."], stability:"Counts are exact integers; convert once to floating point and guard the empty-node denominator." };
  if (c.includes("hinge") || c.includes("margin")) return { intuition:"A margin classifier wants the correct signed score to be at least one. Hinge loss is zero outside the margin and linear when a point violates it.", equation:String.raw`\mathcal L(w,b)=\frac{\lambda}{2}\lVert w\rVert_2^2+\frac1n\sum_{i=1}^{n}\max\!\left(0,1-y_i(w^\top x_i+b)\right)`, symbols:[["w,b","hyperplane parameters"],["y_i","label in {-1,+1}"],["lambda","regularization strength"],["n","number of examples"]], derivation:["Compute the linear score.","Multiply by the signed label.","Compare the signed margin with one.","Keep only positive violations.","Add the quadratic parameter penalty."], workedExample:"If y=+1 and the score is 0.4, the margin is 0.4 and hinge loss is 0.6. A score of 1.3 has zero hinge loss, although regularization still acts on the weights.", codeBridge:["Vectorize scores as X @ w + b.","Use maximum(0, 1 - y*scores).","Average data loss before adding regularization."], stability:"Feature standardization keeps gradient scales comparable and makes the regularization coefficient interpretable." };
  if (c.includes("attention")) return { intuition:"Attention is a learned lookup. Each query scores every key, softmax converts scores into a distribution, and that distribution mixes the values.", equation:String.raw`\operatorname{Attn}(Q,K,V)=\operatorname{softmax}\!\left(\frac{QK^\top+M}{\sqrt{d_k}}\right)V`, symbols:[["Q","queries"],["K","keys"],["V","values"],["M","mask containing 0 or negative infinity"],["d_k","key dimension"]], derivation:["Take every query-key dot product.","Scale by the square root of key width.","Add padding or causal masks.","Normalize each query row with stable softmax.","Use the weights to form a weighted value sum."], workedExample:"For one query with raw scores [2,1], stable softmax subtracts 2 and normalizes [1,e^-1], producing about [0.731,0.269]. The output is 0.731 v1 + 0.269 v2.", codeBridge:["Track shapes as batch, heads, query, key, width.","Apply masks before softmax.","Assert every unmasked attention row sums to one."], stability:"Subtract each row maximum before exponentiation; use a finite mask sentinel only when the dtype cannot safely represent negative infinity." };
  if (c.includes("softmax") || c.includes("sampling") || c.includes("policy")) return { intuition:"Softmax converts relative logits into positive normalized probabilities while temperature controls how strongly differences are expressed.", equation:String.raw`p_i=\frac{\exp((z_i-m)/\tau)}{\sum_j\exp((z_j-m)/\tau)},\qquad m=\max_j z_j`, symbols:[["z_i","logit for outcome i"],["m","maximum logit"],["tau","temperature"],["p_i","normalized probability"]], derivation:["Divide logits by temperature.","Find the maximum scaled logit.","Subtract it without changing probability ratios.","Exponentiate the shifted values.","Divide by their sum."], workedExample:"Logits [1000,999] overflow naively. Subtracting 1000 gives [0,-1], whose probabilities are approximately [0.731,0.269].", codeBridge:["Reduce maximum with keepdims.","Use the same axis for maximum and sum.","Test translation invariance by adding a constant to every logit."], stability:"Maximum subtraction prevents overflow; log-softmax should use log-sum-exp rather than taking log after a rounded probability." };
  if (c.includes("bellman") || c.includes("q-table") || c.includes("bootstrapping") || c.includes("dqn")) return { intuition:"The Bellman target turns a long-horizon problem into a one-step consistency condition between the present estimate and the best estimated continuation.", equation:String.raw`Q(s,a)\leftarrow Q(s,a)+\alpha\left[r+\gamma(1-d)\max_{a'}Q(s',a')-Q(s,a)\right]`, symbols:[["Q(s,a)","current action-value estimate"],["alpha","learning rate"],["r","observed reward"],["gamma","discount factor"],["d","terminal indicator"]], derivation:["Observe one transition.","Evaluate legal next actions.","Remove continuation value at terminal states.","Form reward plus discounted continuation.","Move the old estimate toward that target."], workedExample:"With Q=0.2, reward 0, gamma 0.9, next maximum 0.8, and alpha 0.5, the target is 0.72 and the updated Q is 0.46.", codeBridge:["Mask illegal next actions.","Use a terminal flag in the target.","Log TD error before applying the update."], stability:"Large rewards or aggressive learning rates can destabilize bootstrapping; normalize rewards and inspect target distributions." };
  if (c.includes("lora")) return { intuition:"LoRA constrains a weight update to a low-rank product, preserving the frozen base matrix while training far fewer parameters.", equation:String.raw`W'=W+\frac{\alpha}{r}BA,\qquad A\in\mathbb R^{r\times d_{in}},\quad B\in\mathbb R^{d_{out}\times r}`, symbols:[["W","frozen base weight"],["A,B","trainable low-rank factors"],["r","adapter rank"],["alpha","adapter scaling"]], derivation:["Keep the pretrained transformation fixed.","Project the input into r adapter features.","Project those features back to output width.","Scale the update by alpha/r.","Add the adapter output to the base output."], workedExample:"A 4096 by 4096 matrix has about 16.8M weights. Rank-8 factors require 8*(4096+4096)=65,536 trainable values, roughly 0.39% of the full matrix.", codeBridge:["Initialize A randomly and B at zero so the initial update is zero.","Attach adapters only to selected linear modules.","Report trainable and total parameter counts."], stability:"Adapter scaling and optimizer precision affect early updates; keep sensitive optimizer state in sufficient precision." };
  if (c.includes("fedavg")) return { intuition:"Federated averaging combines client models in proportion to the amount of local evidence they represent.", equation:String.raw`w_{t+1}=\sum_{k\in\mathcal S_t}\frac{n_k}{\sum_{j\in\mathcal S_t}n_j}w_{t+1}^{(k)}`, symbols:[["w_t","global parameters"],["S_t","selected clients"],["n_k","client sample count"],["w^(k)","locally trained parameters"]], derivation:["Broadcast the same global state.","Train selected clients locally.","Count the examples represented by each update.","Normalize client weights by participating sample count.","Sum every parameter tensor with those weights."], workedExample:"Clients with 20 and 80 samples produce scalar parameters 1 and 3. The weighted result is 0.2*1+0.8*3=2.6, not the unweighted mean 2.", codeBridge:["Clone state dictionaries before local training.","Aggregate every key with identical dtype and shape.","Test equivalence with centralized averaging for a controlled case."], stability:"Many local steps on heterogeneous data increase client drift; track update norms and subgroup performance." };
  if (c.includes("expected value") || c.includes("spread") || c.includes("inventory")) return { intuition:"Expected value averages outcomes under their probabilities, while a market-making quote must also price uncertainty, adverse selection, and inventory exposure.", equation:String.raw`\mathbb E[X]=\sum_x x\,p(x),\qquad b=f-s-\kappa q,\quad a=f+s-\kappa q`, symbols:[["f","estimated fair value"],["s","half spread"],["q","inventory"],["kappa","inventory-risk coefficient"],["b,a","bid and ask"]], derivation:["Enumerate mutually exclusive outcomes.","Assign normalized probabilities.","Compute probability-weighted payoff.","Choose a spread for uncertainty and adverse selection.","Shift both quotes against existing inventory."], workedExample:"If a fair value is 50, half-spread is 2, inventory is +3, and kappa is 0.5, quotes become bid 46.5 and ask 50.5, encouraging inventory-reducing sells.", codeBridge:["Separate fair-value estimation from quoting.","Record fills and mark inventory consistently.","Simulate many seeded episodes and inspect the full P&L distribution."], stability:"Expected profit is incomplete without tail loss, path dependence, inventory bounds, and regime sensitivity." };
  return { intuition:`${concept} is a transformation whose meaning comes from its domain, codomain, objective, and invariants. The equation is useful only when every symbol maps to a concrete tensor, state, or measurement.`, equation:String.raw`y=f_\theta(x),\qquad \theta^*=\arg\min_\theta\frac1n\sum_{i=1}^{n}\ell(f_\theta(x_i),y_i)+\lambda\Omega(\theta)`, symbols:[["x,y","input and target"],["f_theta","parameterized transformation"],["ell","data objective"],["Omega","regularizer"],["lambda","regularization weight"]], derivation:["Specify the input representation.","Define the parameterized transformation.","Choose a loss connected to desired behavior.","Average over the training evidence.","Add explicit inductive bias or constraints."], workedExample:"For a one-parameter predictor f(x)=theta*x with x=2, y=6, squared loss is (2theta-6)^2. The minimum without regularization is theta=3.", codeBridge:["Give every axis a semantic name.","Implement a scalar reference first.","Compare optimized output and gradients against the reference."], stability:"Normalize scales, guard invalid domains, and derive tolerances from the operation rather than choosing them after observing failures." };
}

export function buildMathTopics(project: Project): MathTopic[] {
  const conceptTopics = project.concepts.map((concept) => ({ title: concept, ...topicFor(concept) }));
  return [...conceptTopics,
    { title:"Optimization and parameter updates", ...topicFor("objective and gradient update") },
    { title:"Probability, normalization, and calibration", ...topicFor("softmax probability") },
    { title:"Evaluation uncertainty and error bars", intuition:"A reported metric is an estimate from finite evidence. Uncertainty separates stable improvement from sampling noise.", equation:String.raw`\bar x=\frac1n\sum_{i=1}^n x_i,\qquad \operatorname{SE}(\bar x)=\frac{s}{\sqrt n},\qquad \mathrm{CI}_{95\%}\approx\bar x\pm1.96\operatorname{SE}`, symbols:[["x_i","per-example or per-run measurement"],["x-bar","sample mean"],["s","sample standard deviation"],["n","independent observations"]], derivation:["Choose the independent unit.","Compute one measurement per unit.","Estimate mean and sample variance.","Convert variation into standard error.","Report an interval with assumptions or use bootstrap resampling."], workedExample:"Five seeded scores with mean 0.80 and standard deviation 0.04 have SE about 0.0179, giving a rough 95% interval 0.765 to 0.835.", codeBridge:["Store per-example and per-seed values, not only the average.","Use stratified or paired intervals when the design requires them.","Never treat correlated tokens or timesteps as independent runs."], stability:"Uncertainty formulas fail when independence, stationarity, or bounded-variance assumptions are badly violated; use design-aware resampling." },
  ];
}
