import type { StepLocation } from "@/lib/walkthroughs";

export function ConceptDiagram({ location }: { location: StepLocation }) {
  const topic = `${location.part.title} ${location.step.title}`.toLowerCase();
  if (topic.includes("connect-4") || topic.includes("board")) return <figure className="concept-diagram board-diagram" aria-label="Connect-4 board coordinate diagram"><div>{Array.from({length:42},(_,i)=><i className={i%9===0?"filled":""} key={i}/>)}</div><figcaption><strong>6 rows × 7 columns</strong><span>Rows grow downward; pieces occupy the lowest free cell.</span></figcaption></figure>;
  if (topic.includes("attention") || topic.includes("transformer")) return <figure className="concept-diagram flow-diagram" aria-label="Attention data flow"><div><b>Tokens</b><span>→</span><b>Q · Kᵀ</b><span>→</span><b>Softmax</b><span>→</span><b>× V</b></div><figcaption><strong>Attention flow</strong><span>Scores choose which value vectors matter for each token.</span></figcaption></figure>;
  if (topic.includes("mcts") || topic.includes("tree search")) return <figure className="concept-diagram tree-diagram" aria-label="Monte Carlo tree search diagram"><div className="tree-root">state</div><div className="tree-edge"/><div className="tree-level"><b>explore</b><b className="chosen">best PUCT</b><b>exploit</b></div><figcaption><strong>Selection → expansion → backup</strong><span>Visit counts turn repeated simulations into a stronger policy.</span></figcaption></figure>;
  if (topic.includes("retrieval") || topic.includes("embedding") || topic.includes("rag")) return <figure className="concept-diagram flow-diagram" aria-label="Retrieval augmented generation flow"><div><b>Documents</b><span>→</span><b>Chunks</b><span>→</span><b>Vectors</b><span>→</span><b>Top-k context</b><span>→</span><b>Answer</b></div><figcaption><strong>Grounded generation</strong><span>The answer receives only the evidence selected by retrieval.</span></figcaption></figure>;
  if (topic.includes("cuda") || topic.includes("kernel") || topic.includes("gpu")) return <figure className="concept-diagram gpu-diagram" aria-label="GPU grid block and thread hierarchy"><div>{Array.from({length:12},(_,block)=><span key={block}>{Array.from({length:16},(_,thread)=><i key={thread}/>)}</span>)}</div><figcaption><strong>Grid → blocks → threads</strong><span>Nearby threads cooperate through fast shared memory.</span></figcaption></figure>;
  return <figure className="concept-diagram flow-diagram" aria-label="Machine learning implementation loop"><div><b>Input</b><span>→</span><b>{location.step.title.replaceAll("_"," ")}</b><span>→</span><b>Check</b><span>→</span><b>Integrate</b></div><figcaption><strong>One dependable step</strong><span>Small verified contracts compose into the complete project.</span></figcaption></figure>;
}
